Repository cisagov/skeleton-packer-cool, pull requests merged in 2020-03, with the labels that each got.

#2 Merge latest changes from skeleton-packer / fix pre-commit cache issue
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  .gitignore
  .mdl_config.json
  .pre-commit-config.yaml
Labels: bugfix

#3 Cherry pick merge #10 from Kali-packer
  terraform-post-packer/main.tf
Labels: enhancement

#5 Use ami-build-iam-user-tf-module
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  README.md
  src/version.txt
  terraform-test-user/main.tf
  terraform-test-user/remote_states.tf
Labels: enhancement

#6 Update from skeleton-packer
  README.md
Labels: documentation

#8 Update the account lookup regex
  terraform-post-packer/main.tf
Labels: bugfix
